import json
from core.colors import Colors

class NPXAdvancedReport:
    def __init__(self, framework):
        self.framework = framework

    def generate_html_report(self, vulnerabilities, exploits, filename="npx_report.html"):
        """توليد تقرير HTML احترافي"""
        target = self.framework.config.target_url or "No target"
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NPX Framework Security Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ background: #0a0a0f; color: #e0e5f0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 20px; }}
        .container {{ max-width: 1000px; margin: 0 auto; }}
        .header {{ background: linear-gradient(135deg, #6fffe0, #a78bfa); padding: 30px; border-radius: 16px; text-align: center; margin-bottom: 30px; }}
        .header h1 {{ color: #0a0a0f; font-size: 2.2rem; }}
        .header p {{ color: #1a1a2e; opacity: 0.8; }}
        .section {{ background: rgba(255,255,255,0.03); border: 1px solid rgba(111,255,224,0.1); border-radius: 12px; padding: 20px; margin-bottom: 20px; }}
        .section h2 {{ color: #6fffe0; margin-bottom: 15px; border-bottom: 1px solid rgba(111,255,224,0.1); padding-bottom: 10px; }}
        .vuln {{ background: rgba(255,0,0,0.08); border-left: 4px solid #ff4444; padding: 12px 16px; margin: 8px 0; border-radius: 6px; }}
        .exploit {{ background: rgba(0,255,0,0.08); border-left: 4px solid #44ff44; padding: 12px 16px; margin: 8px 0; border-radius: 6px; }}
        .info {{ background: rgba(255,255,0,0.08); border-left: 4px solid #ffcc00; padding: 12px 16px; margin: 8px 0; border-radius: 6px; }}
        .badge {{ display: inline-block; padding: 2px 12px; border-radius: 20px; font-size: 0.75rem; font-weight: 600; }}
        .badge.critical {{ background: #ff4444; color: #fff; }}
        .badge.high {{ background: #ff8800; color: #fff; }}
        .badge.medium {{ background: #ffcc00; color: #000; }}
        .badge.low {{ background: #44ff44; color: #000; }}
        .footer {{ text-align: center; margin-top: 30px; color: rgba(255,255,255,0.2); font-size: 0.8rem; }}
        .stats-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 15px; margin: 15px 0; }}
        .stat-card {{ background: rgba(255,255,255,0.03); border-radius: 10px; padding: 15px; text-align: center; border: 1px solid rgba(111,255,224,0.05); }}
        .stat-card .number {{ font-size: 2rem; font-weight: 700; color: #6fffe0; }}
        .stat-card .label {{ color: rgba(255,255,255,0.4); font-size: 0.8rem; }}
        a {{ color: #6fffe0; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🛡️ NPX Framework Security Assessment</h1>
            <p>Target: <strong>{target}</strong></p>
            <p style="font-size:0.9rem;"><a href="https://npx-official.github.io/">https://npx-official.github.io/</a></p>
        </div>
        
        <div class="section">
            <h2>📊 Summary</h2>
            <div class="stats-grid">
                <div class="stat-card">
                    <div class="number">{len(vulnerabilities)}</div>
                    <div class="label">Vulnerabilities</div>
                </div>
                <div class="stat-card">
                    <div class="number">{len(exploits)}</div>
                    <div class="label">Exploits</div>
                </div>
            </div>
        </div>

        <div class="section">
            <h2>⚠️ Vulnerabilities Found</h2>
            {''.join([f'<div class="vuln"><strong>Type:</strong> {v.get("type","Unknown")}<br><strong>URL:</strong> {v.get("url","N/A")}<br><strong>Details:</strong> {v.get("details","N/A")}</div>' for v in vulnerabilities]) if vulnerabilities else '<p style="color:rgba(255,255,255,0.3);">No vulnerabilities detected.</p>'}
        </div>

        <div class="section">
            <h2>💥 Exploits Achieved</h2>
            {''.join([f'<div class="exploit"><strong>Type:</strong> {e.get("type","Unknown")}<br><strong>URL:</strong> {e.get("url","N/A")}<br><strong>Details:</strong> {e.get("details","N/A")}</div>' for e in exploits]) if exploits else '<p style="color:rgba(255,255,255,0.3);">No exploits executed.</p>'}
        </div>

        <div class="footer">
            <p>Generated by NPX Framework v1.0 | &copy; 2026</p>
        </div>
    </div>
</body>
</html>"""
        with open(filename, 'w') as f:
            f.write(html)
        print(f"{Colors.OKGREEN}[+] HTML report saved to {filename}{Colors.ENDC}")

    def run(self, vulnerabilities, exploits):
        print(f"{Colors.OKCYAN}[*] Generating reports...{Colors.ENDC}")
        self.generate_html_report(vulnerabilities, exploits)
